using Microsoft.AspNetCore.Authorization;
using RoadmapPlatform.Infrastructure.Security;

namespace RoadmapPlatform.Api.Extensions
{
    // Class này dùng để cấu hình Authorization cho API.
    // Những phần nên đặt ở đây gồm: role policies, permission policies,
    // custom authorization requirements, authorization handlers, fallback policy,
    // và các rule kiểm tra quyền truy cập endpoint.
    // Authorization trả lời câu hỏi: "Người dùng này được phép làm gì?"
    public static class ApiAuthorizationExtensions
    {
        public static IServiceCollection AddApiAuthorization(this IServiceCollection services)
        {
            services.AddAuthorization(options =>
            {
                // Static policies can still be registered here when needed.
                // Permission policies are generated by PermissionPolicyProvider
                // only for policy names prefixed with Permission:.
            });

            services.AddSingleton<IAuthorizationPolicyProvider, PermissionPolicyProvider>();

            return services;
        }
    }
}
