-- Shared skills used by more than one roadmap seed.
-- Run this before the individual roadmap seed files.
-- Idempotent and safe to rerun even if some roadmap seeds were already applied.
-- Re-evaluated so reusable, counselor-facing skills live here as the source of truth.

BEGIN;

DROP TABLE IF EXISTS seed_shared_skill;
CREATE TEMP TABLE seed_shared_skill (
    slug text PRIMARY KEY,
    name text NOT NULL UNIQUE,
    category text NOT NULL,
    description text NOT NULL
) ON COMMIT DROP;

INSERT INTO seed_shared_skill (slug, name, category, description)
VALUES

('a-b-testing', 'A/B Testing', 'Software Quality', 'Designing controlled experiments with variants, metrics, randomization, sample sizing, statistical interpretation, and decision criteria.'),
('accessibility', 'Accessibility', 'Design & UX', 'Designing and implementing software that works with assistive technologies, keyboard navigation, semantic structure, contrast, and adaptable content.'),
('accessibility-testing', 'Accessibility Testing', 'Software Quality', 'Evaluating software with accessibility checks, keyboard flows, screen readers, semantic markup, contrast, and issue reporting.'),
('advanced-specializations', 'Advanced Specializations', 'Career & Communication', 'Exploring advanced role-specific tracks while comparing prerequisites, learning depth, portfolio value, and career fit.'),
('ai-assisted-analysis', 'AI-Assisted Analysis', 'Data & Analytics', 'Using AI to explore data, generate hypotheses, summarize patterns, check assumptions, validate outputs, and support analyst workflows.'),
('airflow', 'Airflow', 'Data Engineering', 'Orchestrating data workflows with Airflow DAGs, tasks, schedules, dependencies, retries, backfills, and operational monitoring.'),
('analytics-case-interviews', 'Analytics Case Interviews', 'Data & Analytics', 'Solving ambiguous business cases by clarifying goals, defining metrics, asking for data, and recommending action.'),
('analytics-engineering', 'Analytics Engineering', 'Data Engineering', 'Understanding extraction, transformation, loading, warehouse-first transformation, and operational tradeoffs.'),
('analytics-lifecycle', 'Analytics Lifecycle', 'Data & Analytics', 'Understanding how questions move from business problem to data sourcing, modeling, analysis, visualization, delivery, and iteration.'),
('android-development', 'Android Development', 'Mobile Development', 'Understanding native and cross-platform ecosystems, tooling, app stores, SDKs, and team tradeoffs.'),
('angular', 'Angular', 'Frontend', 'Building Angular applications with components, templates, services, routing, forms, dependency injection, and application structure.'),
('anomaly-detection', 'Anomaly Detection', 'AI & Machine Learning', 'Detecting unusual behavior with baselines, thresholds, outlier methods, time windows, alert signals, and model or rule-based techniques.'),
('ansible', 'Ansible', 'DevOps & Platform', 'Writing inventories and playbooks for package installation, configuration files, services, and idempotent tasks.'),
('api', 'API', 'Backend', 'Designing and consuming APIs with endpoints, request and response contracts, authentication, validation, status codes, versioning, and error handling.'),
('api-client-design', 'API Client Design', 'Backend', 'Designing API clients with typed requests, response parsing, retries, cancellation, authentication, error handling, and integration boundaries.'),
('api-data-extraction', 'API Data Extraction', 'Data Engineering', 'Extracting data from APIs with authentication, pagination, rate limits, schema handling, retries, incremental loading, and error recovery.'),
('api-data-ingestion', 'API Data Ingestion', 'Data Engineering', 'Loading API data into reliable storage with extraction logic, scheduling, validation, schema checks, deduplication, and failure handling.'),
('api-security', 'API Security', 'Cybersecurity', 'Protecting APIs with validation, rate limits, auth checks, secret management, logging, and least privilege.'),
('app-store-release', 'App Store Release', 'Mobile Development', 'Creating pre-release checklists for functionality, permissions, performance, accessibility, and store readiness.'),
('appium-testing', 'Appium Testing', 'Software Quality', 'Automating native, hybrid, and mobile web apps using Appium concepts and drivers.'),
('asynchronous-javascript', 'Asynchronous JavaScript', 'Programming', 'Using callbacks, promises, async/await, error handling, cancellation awareness, and concurrency patterns.'),
('authentication', 'Authentication', 'Cybersecurity', 'Verifying user or service identity through credentials, sessions, tokens, MFA, federation, and secure login flows.'),
('authorization', 'Authorization', 'Cybersecurity', 'Controlling access with roles, permissions, policies, scopes, ownership rules, and enforcement checks across application boundaries.'),
('aws', 'AWS', 'Cloud & Infrastructure', 'Using AWS services for identity, compute, storage, networking, databases, monitoring, automation, and cost-aware cloud operations.'),
('azure', 'Azure', 'Cloud & Infrastructure', 'Using Azure services for identity, compute, storage, networking, monitoring, deployment, governance, and cloud operations.'),
('backend-technology-selection', 'Backend Technology Selection', 'Backend', 'Comparing backend languages, frameworks, ecosystems, runtime constraints, team skills, deployment fit, and tradeoffs.'),
('bash', 'Bash', 'Systems & Operating Systems', 'Writing scripts using variables, conditions, loops, functions, exit codes, and argument parsing.'),
('bias-and-fairness', 'Bias and Fairness', 'AI & Machine Learning', 'Assess fairness risks, subgroup performance, representation gaps, and mitigation options.'),
('bigquery', 'BigQuery', 'Data & Analytics', 'Analyzing data in BigQuery with SQL, partitioning, clustering, warehouse storage, query cost awareness, and reporting workflows.'),
('bitbucket', 'Bitbucket', 'Tools & Workflow', 'Managing repositories, pull requests, branches, permissions, pipelines, and team collaboration workflows in Bitbucket.'),
('browser-storage', 'Browser Storage', 'Frontend', 'Using cookies, local storage, session storage, and IndexedDB while considering persistence, quota, serialization, security, and browser behavior.'),
('business-metrics', 'Business Metrics', 'Data & Analytics', 'Turn vague requests into measurable questions, define KPIs, and identify what decision the analysis should support.'),
('business-process-mapping', 'Business Process Mapping', 'Business & Product', 'Documenting business workflows, actors, handoffs, systems, decisions, and pain points so requirements can be improved or automated.'),
('capacity-planning', 'Capacity Planning', 'Architecture & System Design', 'Estimate data volume, throughput, storage, compute, partitioning, retention, and query concurrency needs.'),
('career-planning', 'Career Planning', 'Career & Communication', 'Map goals to Security+, ISC2 CC, cloud/security certs, blue-team certs, or practical pentest certs.'),
('chart-selection', 'Chart Selection', 'Data & Analytics', 'Selecting bar, line, area, scatter, heatmap, table, card, waterfall, funnel, and map visuals appropriately.'),
('ci-cd', 'CI/CD', 'DevOps & Platform', 'Running build, test, lint, migration checks, and deployment steps automatically.'),
('client-side-routing', 'Client-Side Routing', 'Frontend', 'Implementing route definitions, navigation state, nested routes, parameters, redirects, guards, and browser history behavior.'),
('cloud-architecture', 'Cloud Architecture', 'Cloud & Infrastructure', 'Applying cloud architecture basics to production reliability work with observable evidence, operational safeguards, and clear handoff notes.'),
('cloud-computing', 'Cloud Computing', 'Cloud & Infrastructure', 'Understanding VPCs, subnets, routing, NAT, firewalls, load balancers, and private service access.'),
('cloud-cost-optimization', 'Cloud Cost Optimization', 'Cloud & Infrastructure', 'Estimate capacity needs, test load behavior, identify bottlenecks, and plan safe scaling or resilience improvements.'),
('cloud-migration', 'Cloud Migration', 'Cloud & Infrastructure', 'Cloud Migration is demonstrated through identity, networking, compute, storage, managed services, security, reliability, and cost controls.'),
('cloud-monitoring', 'Cloud Monitoring', 'Cloud & Infrastructure', 'Effective Cloud Monitoring combines identity, networking, compute, storage, managed services, security, reliability, and cost controls.'),
('cloud-networking', 'Cloud Networking', 'Cloud & Infrastructure', 'Understanding private endpoints, VPC/VNet basics, firewall rules, service connectivity, and data egress.'),
('cloud-security', 'Cloud Security', 'Cybersecurity', 'Secure VPC/VNet design, security groups, private endpoints, egress, and segmentation.'),
('cloud-storage', 'Cloud Storage', 'Cloud & Infrastructure', 'Understanding buckets/containers, CSV/Parquet files, folders, access policies, and data lake zones.'),
('clustering', 'Clustering', 'AI & Machine Learning', 'Using k-means, hierarchical clustering, DBSCAN, and cluster validation.'),
('cohort-analysis', 'Cohort Analysis', 'Data & Analytics', 'Grouping users/customers by start period or behavior and analyze retention, revenue, and lifecycle changes.'),
('command-line', 'Command Line', 'Systems & Operating Systems', 'Navigate files, run commands, inspect logs, use environment variables, and execute scripts.'),
('community-management', 'Community Management', 'Career & Communication', 'Effective Community Management combines technical evidence, audience needs, concise explanation, tradeoffs, portfolio framing, and role readiness.'),
('confidence-intervals', 'Confidence Intervals', 'Mathematics & Theory', 'Estimate uncertainty and communicate ranges rather than overconfident point estimates.'),
('configuration-management', 'Configuration Management', 'DevOps & Platform', 'Applying configuration management to production reliability work with observable evidence, operational safeguards, and clear handoff notes.'),
('containerization', 'Containerization', 'DevOps & Platform', 'Understanding Linux containers, virtual machines, isolation, images, and runtime tradeoffs.'),
('core-web-vitals', 'Core Web Vitals', 'Frontend', 'Measure LCP, INP, CLS, and user-perceived performance with practical diagnostic tools.'),
('correlation-vs-causation', 'Correlation vs Causation', 'Data & Analytics', 'Avoid causal claims from descriptive BI and identify confounders and alternative explanations.'),
('cplusplus-for-unreal-and-engine-systems', 'C++ for Unreal and Engine Systems', 'Game Development', 'C++ for Unreal and Engine Systems covers engine systems, player behavior, content workflows, performance, debugging, persistence, and iterative playtesting.'),
('csharp', 'C#', 'Programming', 'Writing C# applications with types, classes, LINQ, async patterns, error handling, tooling, and maintainable object-oriented structure.'),
('csharp-for-unity-gameplay', 'C# for Unity Gameplay', 'Game Development', 'Working with C# for Unity Gameplay requires sound decisions about engine systems, player behavior, content workflows, performance, debugging, persistence, and iterative playtesting.'),
('css', 'CSS', 'Frontend', 'Styling web interfaces with selectors, cascade, specificity, box model, layout systems, responsive behavior, and maintainable style organization.'),
('cypress', 'Cypress', 'Software Quality', 'Configuring Cypress projects with the test runner, selectors, fixtures, network stubbing, debugging tools, and CI execution.'),
('cypress-testing', 'Cypress Testing', 'Software Quality', 'Writing Cypress end-to-end and component tests with assertions, fixtures, selectors, user flows, and browser automation.'),
('dart', 'Dart', 'Mobile Development', 'Writing Dart code for Flutter applications with null safety, asynchronous programming, collections, classes, packages, and UI-oriented patterns.'),
('dashboard-design', 'Dashboard Design', 'Data & Analytics', 'Designing dashboards around user goals, metric hierarchy, layout, chart choice, filters, annotations, and decision-making flow.'),
('dashboard-documentation', 'Dashboard Documentation', 'Tools & Workflow', 'Documenting definitions, refresh cadence, data lineage, known caveats, and support channels.'),
('dashboard-performance', 'Dashboard Performance', 'Data & Analytics', 'Improving dashboard speed through query tuning, model design, aggregation, caching, extract strategy, and visual simplification.'),
('dashboard-quality-assurance', 'Dashboard Quality Assurance', 'Software Quality', 'Testing dashboard filters, row counts, metric definitions, permissions, freshness, visual labels, and stakeholder acceptance criteria.'),
('data-catalogs', 'Data Catalogs', 'Data Engineering', 'Using catalogs to discover assets, owners, glossary terms, lineage, quality signals, and documentation.'),
('data-cleaning', 'Data Cleaning', 'Data & Analytics', 'Preparing data by fixing missing values, duplicates, formats, outliers, invalid records, inconsistent categories, and quality issues.'),
('data-contracts', 'Data Contracts', 'Data Engineering', 'Defining producer/consumer expectations for fields, types, nullability, freshness, and breaking changes.'),
('data-governance', 'Data Governance', 'Data Engineering', 'Understanding stewardship, ownership, policies, definitions, cataloging, lineage, and certification.'),
('data-lineage', 'Data Lineage', 'Data Engineering', 'Trace fields from source to transformation to model to dashboard and communicate downstream impact.'),
('data-literacy', 'Data Literacy', 'Data & Analytics', 'Read tables, fields, grain, joins, aggregations, filters, distributions, and caveats with confidence.'),
('data-modeling', 'Data Modeling', 'Database', 'Understanding facts, dimensions, grain, slowly changing attributes, and why BI-ready schemas reduce metric confusion.'),
('data-profiling', 'Data Profiling', 'Data & Analytics', 'Profile columns, nulls, distributions, categories, uniqueness, relationships, and anomalies before modeling.'),
('data-quality', 'Data Quality', 'Data & Analytics', 'Recognizing missing values, duplicates, inconsistent definitions, outliers, stale data, and source-system limitations.'),
('data-quality-dimensions', 'Data Quality Dimensions', 'Data & Analytics', 'Measure completeness, accuracy, consistency, timeliness, uniqueness, validity, and integrity.'),
('data-storytelling', 'Data Storytelling', 'Data & Analytics', 'Turn analysis results into a clear narrative with context, evidence, limitations, and actionable recommendations.'),
('data-tests', 'Data Tests', 'Software Quality', 'Using uniqueness, not-null, accepted-values, relationships, custom tests, and business rule checks.'),
('data-validation', 'Data Validation', 'Data & Analytics', 'Checking data against expected types, ranges, completeness, uniqueness, business rules, and source-system assumptions before analysis.'),
('data-visualization', 'Data Visualization', 'Data & Analytics', 'Applying Data Visualization means working with appropriate encodings, scales, comparison structure, accessibility, annotation, and truthful interpretation.'),
('dbt', 'dbt', 'Data Engineering', 'Building dbt projects with models, sources, tests, documentation, materializations, dependencies, and deployment jobs.'),
('deep-learning-and-neural-networks', 'Deep Learning and Neural Networks', 'AI & Machine Learning', 'Working with Deep Learning and Neural Networks requires sound decisions about model structure, optimization behavior, numerical stability, and diagnostic interpretation.'),
('descriptive-statistics', 'Descriptive Statistics', 'Mathematics & Theory', 'Using mean, median, mode, percentiles, range, variance, standard deviation, and distribution summaries.'),
('design-tokens-and-theming', 'Design Tokens and Theming', 'Design & UX', 'Defining reusable color, spacing, typography, radius, motion, and theme tokens that keep interfaces visually consistent.'),
('detox-for-react-native', 'Detox for React Native', 'Software Quality', 'Understanding gray-box React Native e2e testing and synchronization concepts.'),
('devops', 'DevOps', 'DevOps & Platform', 'Know when to continue into DevOps topics: Linux, networking, cloud, CI/CD, containers, IaC, observability, and incident response.'),
('distributions-and-sampling', 'Distributions and Sampling', 'Mathematics & Theory', 'Understanding distributions, sampling bias, sample size, and how data collection affects conclusions.'),
('django', 'Django', 'Backend', 'Building backend web applications with Django models, views, routing, forms, authentication, admin tools, and deployment practices.'),
('dns', 'DNS', 'Networking', 'Understanding domain names, DNS records, resolvers, authoritative servers, TTL, and propagation.'),
('docker', 'Docker', 'DevOps & Platform', 'Packaging applications with Docker images, Dockerfiles, containers, volumes, networks, registries, and reproducible runtime configuration.'),
('end-to-end-type-safety', 'End-to-End Type Safety', 'Software Quality', 'Maintaining type guarantees across frontend, backend, API contracts, validation schemas, and generated client code.'),
('environment-management', 'Environment Management', 'Tools & Workflow', 'Handle dev/test/staging/prod differences, config, test data, dependencies, and reset strategies.'),
('error-analysis', 'Error Analysis', 'Data & Analytics', 'Segment model failures by data slice, class, subgroup, and input pattern.'),
('error-handling-and-logging', 'Error Handling and Logging', 'DevOps & Platform', 'Handle expected failures clearly and produce useful logs for debugging.'),
('eslint-and-prettier', 'ESLint and Prettier', 'Tools & Workflow', 'Configuring linting and formatting for JavaScript/TypeScript/frontend frameworks.'),
('etl-vs-elt', 'ETL vs ELT', 'Data Engineering', 'Comparing extraction, transformation timing, orchestration, and cloud warehouse workflows.'),
('evaluation-metrics', 'Evaluation Metrics', 'Data & Analytics', 'Using accuracy, precision, recall, F1, ROC-AUC, PR-AUC, calibration, and confusion matrices.'),
('excel', 'Excel', 'Data & Analytics', 'Using formulas for calculations, conditional logic, text operations, dates, error handling, and reusable analysis fields.'),
('executive-summary-writing', 'Executive Summary Writing', 'Career & Communication', 'Creating short summaries with headline, impact, decision, risks, and next steps.'),
('experiment-tracking', 'Experiment Tracking', 'Data & Analytics', 'Defining experiment goals, metrics, treatment groups, sample considerations, and interpretation rules before analyzing results.'),
('exploratory-data-analysis', 'Exploratory Data Analysis', 'Data & Analytics', 'Exploratory Data Analysis covers question framing, data preparation, metrics, analysis, validation, visualization, and communication.'),
('exploratory-testing', 'Exploratory Testing', 'Software Quality', 'Investigating software behavior without rigid scripts to discover unexpected risks, edge cases, defects, and usability issues.'),
('feature-engineering', 'Feature Engineering', 'AI & Machine Learning', 'Applying Feature Engineering means working with data assumptions, model behavior, evaluation signals, failure modes, safety, and production constraints.'),
('firebase', 'Firebase', 'Cloud & Infrastructure', 'Understanding realtime sync, client subscriptions, live updates, and tradeoffs.'),
('flutter', 'Flutter', 'Mobile Development', 'Understanding Flutter as a cross-platform option and how it differs from web frontend stacks.'),
('frontend-backend-integration', 'Frontend-Backend Integration', 'Frontend', 'Integrate external APIs while handling rate limits, credentials, retries, errors, and terms constraints.'),
('frontend-performance', 'Frontend Performance', 'Frontend', 'Avoid unnecessary rerenders, expensive layout work, blocking scripts, and inefficient data flows.'),
('full-stack-development', 'Full Stack Development', 'Programming', 'Full Stack Development is demonstrated through clear logic, appropriate abstractions, debugging, maintainability, edge cases, and complexity.'),
('full-stack-testing', 'Full Stack Testing', 'Software Quality', 'Testing complete application flows across frontend, backend, database, authentication, integrations, and deployment environments.'),
('funnel-analysis', 'Funnel Analysis', 'Data & Analytics', 'Analyzing conversion steps, drop-offs, segmentation, and bottlenecks in business workflows.'),
('gdscript-for-godot', 'GDScript for Godot', 'Game Development', 'GDScript for Godot covers engine systems, player behavior, content workflows, performance, debugging, persistence, and iterative playtesting.'),
('git', 'Git', 'Tools & Workflow', 'Managing source history with commits, branches, merges, rebases, tags, conflict resolution, and collaborative repository workflows.'),
('github', 'GitHub', 'Tools & Workflow', 'Collaborating on GitHub with repositories, pull requests, issues, reviews, Actions workflows, permissions, and project documentation.'),
('gitlab', 'GitLab', 'Tools & Workflow', 'Understanding GitLab projects, merge requests, issues, and GitLab CI/CD basics.'),
('gitops', 'GitOps', 'DevOps & Platform', 'Understanding declared state, controllers, pull-based deployment, drift detection, and audit history.'),
('go', 'Go', 'Programming', 'Writing Go programs with modules, types, interfaces, goroutines, channels, HTTP services, and command-line tooling.'),
('godot-engine', 'Godot Engine', 'Game Development', 'Godot Engine is demonstrated through engine systems, player behavior, content workflows, performance, debugging, persistence, and iterative playtesting.'),
('google-cloud', 'Google Cloud', 'Cloud & Infrastructure', 'Developing working knowledge of BigQuery, Dataflow, Pub/Sub, GCS, Dataproc, IAM, and common GCP data architecture patterns.'),
('governance-and-guardrails', 'Governance and Guardrails', 'Cybersecurity', 'The practical scope of Governance and Guardrails includes assets, threats, trust boundaries, preventive controls, detection, and response.'),
('gradient-boosting', 'Gradient Boosting', 'AI & Machine Learning', 'Using boosted trees such as XGBoost, LightGBM, or HistGradientBoosting.'),
('grafana-k6', 'Grafana K6', 'DevOps & Platform', 'Using JavaScript-based load scripts, thresholds, checks, scenarios, and metrics analysis.'),
('graphql', 'GraphQL', 'Backend', 'Using schemas, resolvers, queries, mutations, N+1 concerns, and REST-vs-GraphQL tradeoffs.'),
('helm', 'Helm', 'DevOps & Platform', 'Package and parameterize applications using Helm charts and release values.'),
('html', 'HTML', 'Frontend', 'Read simple HTML forms and understand how browsers submit data.'),
('http', 'HTTP', 'Web', 'HTTP is a reusable competency with clear concepts, practical application, validation, and learning-module relevance.'),
('hypothesis-testing', 'Hypothesis Testing', 'Mathematics & Theory', 'Formulating null and alternative hypotheses, choosing suitable tests, interpreting p-values, confidence, power, and practical significance.'),
('iam', 'Identity and Access Management', 'Cybersecurity', 'Applying least-privilege access, authentication rules, encryption controls, and audit evidence for safer database operations.'),
('incident-response', 'Incident Response', 'Cybersecurity', 'Handling incidents with detection, triage, containment, communication, remediation, post-incident review, and prevention follow-up.'),
('infrastructure-as-code', 'Infrastructure As Code', 'DevOps & Platform', 'Automating repeatable database tasks with scripts or infrastructure definitions while protecting credentials and change safety.'),
('internet', 'Internet', 'Networking', 'Understanding internet communication through IP addressing, DNS, routing, HTTP, TLS, service boundaries, and troubleshooting signals.'),
('interview-readiness', 'Interview Readiness', 'Career & Communication', 'Preparing for interviews with role expectations, technical explanations, practice problems, project stories, and concise communication.'),
('ios-development', 'iOS Development', 'Mobile Development', 'The practical scope of iOS Development includes platform lifecycles, navigation, device APIs, local data, performance, accessibility, testing, and release behavior.'),
('ip-addressing-and-subnetting', 'IP Addressing and Subnetting', 'Networking', 'Applying IPv4, IPv6 basics, CIDR, routing boundaries, and subnet planning.'),
('java', 'Java', 'Programming', 'Writing Java applications with classes, interfaces, collections, exceptions, generics, build tools, concurrency basics, and runtime behavior.'),
('javascript', 'JavaScript', 'Programming', 'Writing JavaScript with functions, objects, modules, asynchronous behavior, browser APIs, error handling, and maintainable structure.'),
('jest-and-vitest', 'Jest and Vitest', 'Software Quality', 'Testing JavaScript and TypeScript code with assertions, mocks, fixtures, snapshots, coverage, and continuous integration.'),
('jwt', 'JWT', 'Cybersecurity', 'Using JWTs with claims, signing, expiration, validation, storage risks, and authorization boundaries.'),
('kafka', 'Kafka', 'Data Engineering', 'Understanding topics, partitions, producers, consumers, consumer groups, and event streaming.'),
('kotlin', 'Kotlin', 'Programming', 'Developing working knowledge of Kotlin fundamentals for native Android development.'),
('kubernetes', 'Kubernetes', 'DevOps & Platform', 'Operating Kubernetes workloads with pods, deployments, services, config, secrets, ingress, scaling, updates, and cluster troubleshooting.'),
('linux', 'Linux', 'Systems & Operating Systems', 'Administering Linux systems through the shell, filesystems, permissions, processes, services, networking tools, and logs.'),
('load-balancing', 'Load Balancing', 'Networking', 'Configuring load balancing behavior, health checks, failover expectations, and traffic distribution.'),
('looker', 'Looker', 'Data & Analytics', 'Understanding governed BI concepts using Looker models, explores, dimensions, measures, and shared definitions.'),
('looker-and-looker-studio', 'Looker and Looker Studio', 'Data & Analytics', 'Using Looker semantic modeling and Looker Studio reporting to define governed metrics and deliver interactive analytics.'),
('looker-studio', 'Looker Studio', 'Data & Analytics', 'Creating Looker Studio reports with data sources, calculated fields, filters, charts, sharing, and dashboard maintenance.'),
('loss-functions', 'Loss Functions', 'AI & Machine Learning', 'Selecting losses for classification, regression, ranking, contrastive, and sequence tasks.'),
('maestro-mobile-testing', 'Maestro Mobile Testing', 'Software Quality', 'Automating mobile test flows with Maestro commands, selectors, assertions, device actions, test data, and CI-friendly execution.'),
('metrics', 'Metrics', 'Data & Analytics', 'Defining reliable measures with clear formulas, grain, filters, owners, interpretation notes, and decision context.'),
('mobile-accessibility', 'Mobile Accessibility', 'Mobile Development', 'Making mobile interfaces usable with screen readers, focus order, touch targets, contrast, dynamic type, and platform accessibility APIs.'),
('mobile-development', 'Mobile Development', 'Mobile Development', 'Building mobile applications with platform lifecycles, navigation, device APIs, local storage, performance, accessibility, and release workflows.'),
('mobile-performance', 'Mobile Performance', 'Mobile Development', 'Improving mobile responsiveness, startup time, memory use, network behavior, battery usage, rendering, and crash stability.'),
('mobile-security', 'Mobile Security', 'Cybersecurity', 'Protecting mobile apps with secure storage, transport security, authentication, permissions, dependency hygiene, and tamper awareness.'),
('mobile-testing', 'Mobile Testing', 'Software Quality', 'Testing mobile behavior across devices, OS versions, permissions, network conditions, gestures, notifications, and app lifecycle events.'),
('mobile-ui-ux', 'Mobile UI/UX', 'Mobile Development', 'Designing mobile experiences with touch targets, navigation patterns, gestures, responsiveness, accessibility, and platform expectations.'),
('model-evaluation', 'Model Evaluation', 'AI & Machine Learning', 'Working with model evaluation through inputs, behavior, evaluation criteria, limitations, deployment constraints, and monitoring signals.'),
('model-registry', 'Model Registry', 'AI & Machine Learning', 'Track model versions, stages, metadata, approvals, and deployment candidates.'),
('model-selection', 'Model Selection', 'AI & Machine Learning', 'Working with model selection through inputs, behavior, evaluation criteria, limitations, deployment constraints, and monitoring signals.'),
('model-validation', 'Model Validation', 'AI & Machine Learning', 'Working with model validation through inputs, behavior, evaluation criteria, limitations, deployment constraints, and monitoring signals.'),
('mongodb', 'MongoDB', 'Database', 'Model JSON-like documents, indexes, embedded vs referenced data, and flexible schema tradeoffs.'),
('monitoring', 'Monitoring', 'DevOps & Platform', 'Building dashboards, alerts, SLO-style thinking, health checks, and incident visibility.'),
('mysql', 'MySQL', 'Database', 'Working with MySQL schemas, SQL queries, indexes, joins, transactions, constraints, replication basics, and performance tuning.'),
('networking', 'Networking', 'Networking', 'Designing and troubleshooting connected systems with addressing, routing, switching, protocols, segmentation, and operational diagnostics.'),
('networking-fundamentals', 'Networking Fundamentals', 'Networking', 'Understanding OSI and TCP/IP concepts, addressing, routing, DNS, switching, wireless basics, and troubleshooting workflows.'),
('next-js', 'Next.js', 'Frontend', 'Building routed React apps with layouts, server/client components awareness, data fetching, metadata, and deployment.'),
('nginx', 'NGINX', 'Cloud & Infrastructure', 'Configuring reverse proxying, TLS termination, static assets, upstreams, compression, and forwarded headers.'),
('node-js-and-express', 'Node.js and Express', 'Backend', 'Building backend services with Node.js and Express routing, middleware, request validation, controllers, errors, and deployment behavior.'),
('nosql', 'NoSQL', 'Database', 'Understanding document, key-value, wide-column, and graph databases and when they fit data engineering.'),
('npm', 'npm', 'Tools & Workflow', 'Managing JavaScript packages with npm scripts, dependencies, lockfiles, semantic versioning, registries, and install workflows.'),
('nuxt-js', 'Nuxt.js', 'Frontend', 'Building Vue-based applications with Nuxt routing, server rendering, data fetching, layouts, modules, and deployment options.'),
('oauth', 'OAuth', 'Cybersecurity', 'Implementing OAuth flows with clients, authorization grants, redirects, scopes, tokens, refresh behavior, and secure callback handling.'),
('observability', 'Observability', 'DevOps & Platform', 'Combining logs, metrics, traces, dashboards, alerts, and service context to investigate system behavior and production incidents.'),
('observer-pattern-and-reactive-ui', 'Observer Pattern and Reactive UI', 'Frontend', 'Coordinating UI updates with observable state, subscriptions, event streams, dependency tracking, and reactive rendering behavior.'),
('offline-first', 'Offline-First Apps', 'Mobile Development', 'Designing apps that continue working with local data, sync queues, conflict handling, retries, and network recovery.'),
('offline-vs-online-evaluation', 'Offline vs Online Evaluation', 'AI & Machine Learning', 'Understanding when offline metrics fail and how online experiments validate product impact.'),
('pandas', 'pandas', 'Data & Analytics', 'Read, clean, join, aggregate, validate, and export datasets using pandas.'),
('pandas-data-analysis', 'pandas Data Analysis', 'Data & Analytics', 'Using DataFrames, filtering, joins, groupby, reshape, dates, missing values, and exports.'),
('pandas-dataframes', 'pandas DataFrames', 'Data & Analytics', 'Load, clean, aggregate, join, reshape, and analyze tabular datasets.'),
('performance-analysis', 'Performance Analysis', 'Data & Analytics', 'Measuring performance with benchmarks, profiling, bottleneck investigation, baseline comparison, and improvement validation.'),
('php', 'PHP', 'Programming', 'Writing PHP applications with syntax, arrays, functions, classes, HTTP handling, package management, and server-side templates.'),
('pii-and-sensitive-data', 'PII and Sensitive Data', 'Cybersecurity', 'Identify personal, financial, health, confidential, and regulated data in analytics workflows.'),
('platform-engineering', 'Platform Engineering', 'DevOps & Platform', 'Deepen developer portals, self-service workflows, golden paths, and internal platform product thinking.'),
('playwright', 'Playwright', 'Software Quality', 'Using Playwright for browser automation with contexts, pages, locators, traces, screenshots, and cross-browser execution.'),
('playwright-testing', 'Playwright Testing', 'Software Quality', 'Writing Playwright tests with robust locators, assertions, fixtures, parallel execution, tracing, and CI reports.'),
('pnpm', 'pnpm', 'Tools & Workflow', 'Managing JavaScript workspaces and dependencies with pnpm lockfiles, stores, scripts, workspace filters, and reproducible installs.'),
('portfolio-communication', 'Portfolio Communication', 'Career & Communication', 'Presenting project work with problem context, technical decisions, evidence, screenshots, outcomes, and clear personal reflection.'),
('postgresql', 'PostgreSQL', 'Database', 'Working with PostgreSQL databases through schemas, SQL queries, indexes, transactions, constraints, and operational tuning.'),
('postman', 'Postman', 'Tools & Workflow', 'Creating requests, collections, environments, variables, scripts, assertions, and collection runs.'),
('postman-newman-cli', 'Postman Newman CLI', 'Tools & Workflow', 'Running Postman collections in CI, export reports, and parameterize environments.'),
('power-bi', 'Power BI', 'Data & Analytics', 'Building Power BI reports with data models, DAX measures, visuals, filters, refresh configuration, and sharing practices.'),
('power-query', 'Power Query', 'Data & Analytics', 'Transforming BI data with Power Query steps, joins, pivots, type changes, parameters, refresh behavior, and reusable cleaning logic.'),
('privacy-and-data-protection', 'Privacy and Data Protection', 'Cybersecurity', 'Protecting personal data through minimization, consent, retention rules, access controls, encryption, and compliance-aware handling.'),
('production-web-deployment', 'Production Web Deployment', 'DevOps & Platform', 'Deploying static and SSR frontend apps to Vercel, Netlify, or similar platforms.'),
('prompt-injection', 'Prompt Injection', 'Cybersecurity', 'The practical scope of Prompt Injection includes assets, threats, trust boundaries, preventive controls, detection, and response.'),
('python', 'Python', 'Programming', 'Writing Python programs with data structures, functions, modules, virtual environments, file handling, exceptions, packages, and testing basics.'),
('python-syntax-and-control-flow', 'Python Syntax and Control Flow', 'Programming', 'Writing Python basics with variables, conditionals, loops, functions, exceptions, modules, and simple data structures.'),
('python-visualization', 'Python Visualization', 'Data & Analytics', 'Creating analysis visuals with matplotlib, seaborn awareness, Plotly, and business-friendly charts.'),
('pytorch', 'PyTorch', 'AI & Machine Learning', 'Building neural network workflows in PyTorch with tensors, modules, autograd, datasets, optimizers, training loops, and checkpoints.'),
('quality-monitoring', 'Quality Monitoring', 'Software Quality', 'Track freshness, volume, anomalies, failed tests, broken dashboards, and SLA breaches.'),
('query-optimization', 'Query Optimization', 'Database', 'Improving database queries through indexing, execution plans, join strategies, statistics, and measurement of runtime behavior.'),
('rabbitmq', 'RabbitMQ', 'Backend', 'Using queues, exchanges, routing keys, acknowledgements, retries, and dead-letter queues.'),
('react', 'React', 'Frontend', 'Building React interfaces with components, props, state, hooks, rendering behavior, routing integration, and reusable UI patterns.'),
('react-components-and-props', 'React Components and Props', 'Frontend', 'Creating React components with props, composition, conditional rendering, event handling, and reusable UI boundaries.'),
('react-core-architecture', 'React Core Architecture', 'Frontend', 'Organizing React applications with component boundaries, state ownership, data flow, routing, and maintainable feature structure.'),
('react-error-boundaries-and-fallback-ui', 'React Error Boundaries and Fallback UI', 'Frontend', 'Handling React rendering failures with error boundaries, fallback screens, recovery paths, and user-safe failure states.'),
('react-hooks-and-effects', 'React Hooks and Effects', 'Frontend', 'Managing React state and side effects with hooks, dependency arrays, cleanup functions, memoization, and component lifecycle behavior.'),
('react-native', 'React Native', 'Mobile Development', 'Understanding native mobile app development with React components, navigation, platform APIs, and deployment complexity.'),
('react-routing-and-layouts', 'React Routing and Layouts', 'Frontend', 'Structuring React applications with route definitions, nested layouts, URL parameters, navigation state, and protected pages.'),
('recommendation-systems', 'Recommendation Systems', 'AI & Machine Learning', 'Building recommenders with user/item signals, candidate generation, ranking, evaluation metrics, feedback loops, and bias considerations.'),
('redis', 'Redis', 'Database', 'Using Redis for key-value caching, data structures, expiration, pub/sub, persistence tradeoffs, and performance-sensitive access.'),
('relational-databases', 'Relational Databases', 'Database', 'Modeling structured data with tables, relationships, keys, constraints, normalization, transactions, and SQL queries.'),
('release-management', 'Release Management', 'DevOps & Platform', 'Designing delivery workflows with validation, promotion, rollback, and release risk controls.'),
('release-readiness', 'Release Readiness', 'Software Quality', 'Checking whether a release has acceptable quality evidence, known risks, rollback plans, approvals, and monitoring coverage.'),
('reproducible-experiments', 'Reproducible Experiments', 'AI & Machine Learning', 'Control random seeds, environment versions, data snapshots, and configs.'),
('requirements-analysis', 'Requirements Analysis', 'Business & Product', 'Clarifying stakeholder goals, constraints, workflows, acceptance criteria, priorities, and tradeoffs before implementation decisions.'),
('responsible-ai-and-governance', 'Responsible AI and Governance', 'AI & Machine Learning', 'Managing AI systems with safety practices, fairness checks, documentation, policy constraints, monitoring, review processes, and accountability.'),
('responsive-design', 'Responsive Design', 'Frontend', 'Building layouts that adapt across screen sizes with fluid grids, breakpoints, flexible media, typography, and input constraints.'),
('rest-apis', 'REST APIs', 'Backend', 'Designing resource URLs, HTTP methods, status codes, DTOs, validation errors, pagination, filtering, and versioning.'),
('retention-analysis', 'Retention Analysis', 'Data & Analytics', 'Measuring how users continue, return, churn, or re-engage across cohorts, segments, and lifecycle periods.'),
('reverse-proxies', 'Reverse Proxies', 'Networking', 'Applying http, tls, and reverse proxies to production reliability work with observable evidence, operational safeguards, and clear handoff notes.'),
('ruby', 'Ruby', 'Programming', 'Writing Ruby programs with objects, blocks, modules, collections, exceptions, gems, and maintainable idioms.'),
('rust', 'Rust', 'Programming', 'Writing Rust programs with ownership, borrowing, lifetimes, traits, pattern matching, error handling, and Cargo workflows.'),
('secrets-management', 'Secrets Management', 'Cybersecurity', 'Protecting secrets with secure storage, rotation, access controls, environment isolation, scanning, and audit practices.'),
('secure-web-application-development', 'Secure Web Application Development', 'Cybersecurity', 'Building web apps with input validation, authentication, authorization, secure session handling, dependency hygiene, and attack mitigation.'),
('security-headers-and-csp', 'Security Headers and CSP', 'Cybersecurity', 'Configuring browser security headers and Content Security Policy to reduce injection, framing, MIME, and data exposure risks.'),
('select-filtering-and-sorting', 'SELECT, Filtering, and Sorting', 'Database', 'Writing SQL queries that select columns, filter rows, sort results, limit output, and validate returned data.'),
('selenium-webdriver', 'Selenium WebDriver', 'Software Quality', 'Automating browsers with WebDriver concepts, waits, locators, grid, and common Selenium patterns.'),
('semantic-layer', 'Semantic Layer', 'Data & Analytics', 'Defining governed business metrics, dimensions, relationships, access rules, and reusable analytical definitions across tools.'),
('serverless', 'Serverless', 'Cloud & Infrastructure', 'Building event-driven workloads with functions, triggers, managed scaling, cold starts, permissions, observability, and cost behavior.'),
('slowly-changing-dimensions', 'Slowly Changing Dimensions', 'Data Engineering', 'Modeling historical dimension changes with type strategies, effective dates, surrogate keys, current flags, and auditability.'),
('snowflake', 'Snowflake', 'Data Engineering', 'Working with Snowflake warehouses, databases, schemas, roles, stages, SQL transformations, scaling, and cost controls.'),
('spark', 'Spark', 'Data Engineering', 'Understanding drivers, executors, transformations, actions, lazy evaluation, shuffles, and partitions.'),
('spreadsheet-data-cleaning', 'Spreadsheet Data Cleaning', 'Data & Analytics', 'Cleaning spreadsheet data with consistent formats, formulas, validation, deduplication, missing-value handling, and audit-friendly edits.'),
('spreadsheets', 'Spreadsheets', 'Data & Analytics', 'Using spreadsheets for tabular analysis, formulas, pivots, charts, validation, collaboration, and lightweight reporting.'),
('sql', 'SQL', 'Database', 'Know where SQL Server, Oracle, and SQLite fit in backend systems.'),
('sqlite', 'SQLite', 'Database', 'Using SQLite for embedded relational storage with tables, SQL queries, transactions, indexes, constraints, and local application data.'),
('sre-practices', 'SRE Practices', 'DevOps & Platform', 'Explaining why DevOps emphasizes automated workflows, short feedback cycles, reliability, and operational learning.'),
('stakeholder-communication', 'Stakeholder Communication', 'Career & Communication', 'Communicating with stakeholders through clear questions, status updates, risks, tradeoffs, decisions, and audience-aware summaries.'),
('statistics', 'Statistics', 'Mathematics & Theory', 'Using mean, median, variance, quantiles, distributions, and grouped summaries to describe datasets accurately.'),
('survey-analysis', 'Survey Analysis', 'Data & Analytics', 'Analyzing survey data with question design awareness, response cleaning, segmentation, bias checks, and summarized findings.'),
('swift', 'Swift', 'Programming', 'Writing Swift code with optionals, structs, classes, protocols, closures, concurrency, package management, and iOS-oriented patterns.'),
('tableau', 'Tableau', 'Data & Analytics', 'Building visualizations, dashboards, calculated fields, LOD expressions, filters, parameters, and stories.'),
('technical-case-studies', 'Technical Case Studies', 'Career & Communication', 'Writing case studies that explain problem context, constraints, decisions, implementation evidence, results, and lessons learned.'),
('tensorflow', 'TensorFlow', 'AI & Machine Learning', 'Building machine learning workflows in TensorFlow with tensors, layers, datasets, graph execution, training loops, and saved models.'),
('tensorflow-and-keras', 'TensorFlow and Keras', 'AI & Machine Learning', 'Building neural networks with TensorFlow and Keras layers, models, callbacks, optimizers, losses, metrics, and checkpoints.'),
('terraform', 'Terraform', 'DevOps & Platform', 'Provision cloud storage, warehouse resources, IAM, and pipeline infrastructure with reviewable code.'),
('testing', 'Testing', 'Software Quality', 'Designing tests across levels with expected behavior, test data, assertions, defect evidence, automation scope, and release confidence.'),
('time-series-analysis', 'Time Series Analysis', 'Data & Analytics', 'Using pandas date parsing, resampling, rolling windows, and period comparisons for time-based analysis.'),
('training-loops', 'Training Loops', 'AI & Machine Learning', 'Building training, validation, checkpointing, logging, and inference loops.'),
('typescript', 'TypeScript', 'Programming', 'Writing TypeScript with static types, interfaces, generics, narrowing, modules, compiler checks, and maintainable JavaScript integration.'),
('unity-engine', 'Unity Engine', 'Game Development', 'Building games in Unity with scenes, GameObjects, components, prefabs, physics, animation, scripting, and build settings.'),
('unity-netcode-or-mirror', 'Unity Netcode or Mirror', 'Game Development', 'Building Unity multiplayer features with networked objects, authority, synchronization, RPCs, prediction limits, and connection handling.'),
('unreal-engine', 'Unreal Engine', 'Game Development', 'Building games in Unreal with actors, components, Blueprints, C++ classes, levels, materials, and packaging workflow.'),
('unreal-replication', 'Unreal Replication', 'Game Development', 'Synchronizing Unreal multiplayer state with replicated properties, RPCs, ownership, relevancy, authority, and bandwidth constraints.'),
('version-control-for-analysis', 'Version Control for Analysis', 'Data & Analytics', 'Tracking analysis work with commits, branches, reviewable notebooks or scripts, data-change notes, and reproducible history.'),
('vite', 'Vite', 'Frontend', 'Using Vite dev server, config, environment variables, production build, preview, plugins, and dependency pre-bundling.'),
('vue-js', 'Vue.js', 'Frontend', 'Developing working knowledge of Vue components, directives, reactivity, composition API, routing, Pinia, and project structure.'),
('vuepress', 'VuePress', 'Frontend', 'Building documentation sites with VuePress pages, themes, navigation, Markdown content, Vue components, and static deployment.'),
('wcag', 'WCAG', 'Design & UX', 'Understanding perceivable, operable, understandable, and robust accessibility principles.'),
('web-performance-optimization', 'Web Performance Optimization', 'Frontend', 'Find slow queries, avoid N+1 patterns, use indexes, and shape responses for frontend usage.'),
('webpack', 'Webpack', 'Frontend', 'Understanding entries, outputs, loaders, plugins, code splitting, and legacy project maintenance.'),
('window-functions', 'Window Functions', 'Database', 'Writing SQL window functions with partitions, ordering, frames, ranking, offsets, rolling calculations, and grouped comparisons.'),
('workflow-orchestration', 'Workflow Orchestration', 'Data Engineering', 'Using orchestrators such as Airflow, Prefect, Dagster, or Kubeflow concepts.'),
('data-science-workflow', 'Data Science Workflow', 'Data & Analytics', 'Framing analytical questions, collecting data, exploring patterns, modeling, validating results, and communicating decisions in an iterative workflow.'),
('causal-inference', 'Causal Inference', 'Data & Analytics', 'Estimating cause-and-effect relationships with study design, confounding control, assumptions, counterfactual reasoning, and sensitivity checks.'),
('experimental-design', 'Experimental Design', 'Data & Analytics', 'Designing experiments with treatments, controls, randomization, metrics, sample sizing, validity threats, and interpretation plans.'),
('scikit-learn', 'scikit-learn', 'AI & Machine Learning', 'Building machine learning workflows with estimators, pipelines, preprocessing, model selection, metrics, and validation in scikit-learn.'),
('deep-learning', 'Deep Learning', 'AI & Machine Learning', 'Building neural network models with layers, activations, losses, optimizers, regularization, training data, and evaluation metrics.'),
('numpy', 'NumPy', 'Programming', 'Working with numerical arrays, vectorized operations, broadcasting, indexing, and mathematical transformations using NumPy.'),
('service-level-objectives', 'Service Level Objectives', 'DevOps & Platform', 'Defining measurable reliability targets with service indicators, thresholds, time windows, error budgets, and user-impact reasoning.'),
('error-budgets', 'Error Budgets', 'DevOps & Platform', 'Using the allowed reliability gap between target and actual service performance to guide release, risk, and operational decisions.'),
('reliability-engineering', 'Reliability Engineering', 'DevOps & Platform', 'Designing systems and operations for availability, resilience, graceful degradation, recovery, observability, and safe change.'),
('database-administration', 'Database Administration', 'Database', 'Operating databases through configuration, access management, backups, monitoring, maintenance, upgrades, and operational safety practices.'),
('backup-and-recovery', 'Backup and Recovery', 'Database', 'Protecting data with backup strategy, restore testing, point-in-time recovery, retention, replication, and disaster recovery planning.'),
('schema-migrations', 'Schema Migrations', 'Database', 'Changing database schemas safely with versioned migration scripts, rollback planning, compatibility checks, and deployment coordination.'),
('database-observability', 'Database Observability', 'Database', 'Monitoring database health with metrics, logs, slow queries, wait events, replication lag, storage growth, and alerting signals.'),
('runbooks', 'Runbooks', 'DevOps & Platform', 'Documenting repeatable operational procedures for diagnosis, mitigation, escalation, verification, and recovery during production work.'),
('on-call-readiness', 'On-Call Readiness', 'DevOps & Platform', 'Preparing for production support with alert triage, escalation paths, runbooks, incident roles, communication, and fatigue management.'),
('capacity-engineering', 'Capacity Engineering', 'Cloud & Infrastructure', 'Forecasting and testing resource needs for traffic, storage, latency, throughput, scaling limits, and operational headroom.');

-- Update canonical rows that already exist by slug.
UPDATE public.skill s
SET name = ss.name,
    category = ss.category,
    description = ss.description,
    is_active = true
FROM seed_shared_skill ss
WHERE s.slug = ss.slug;

-- Update rows that already exist by name but have a non-canonical slug.
-- Do not force the slug here; this avoids slug unique conflicts if a canonical row also exists.
UPDATE public.skill s
SET category = ss.category,
    description = ss.description,
    is_active = true
FROM seed_shared_skill ss
WHERE s.name = ss.name
  AND NOT EXISTS (
      SELECT 1
      FROM public.skill canonical
      WHERE canonical.slug = ss.slug
  );

-- Insert only missing shared skills. This avoids both slug and name unique conflicts.
INSERT INTO public.skill (slug, name, category, description, is_active)
SELECT ss.slug, ss.name, ss.category, ss.description, true
FROM seed_shared_skill ss
WHERE NOT EXISTS (
    SELECT 1
    FROM public.skill s
    WHERE s.slug = ss.slug OR s.name = ss.name
);

COMMIT;
