-- Shared skills used by more than one roadmap seed.
-- Run this before the individual roadmap seed files.
-- Idempotent and safe to rerun even if some roadmap seeds were already applied.
-- Re-evaluated so reusable, counselor-facing skills live here as the source of truth.

BEGIN;

DROP TABLE IF EXISTS seed_shared_skill;
CREATE TEMP TABLE seed_shared_skill (
    slug text PRIMARY KEY,
    name text NOT NULL UNIQUE,
    category text NOT NULL,
    description text NOT NULL
) ON COMMIT DROP;

INSERT INTO seed_shared_skill (slug, name, category, description)
VALUES










('a-b-testing', 'A/B Testing', 'Software Quality', 'Designing controlled experiments with variants, metrics, randomization, sample sizing, statistical interpretation, and decision criteria.'),
('accessibility', 'Accessibility', 'Design & UX', 'Designing and implementing software that works with assistive technologies, keyboard navigation, semantic structure, contrast, and adaptable content.'),
('accessibility-testing', 'Accessibility Testing', 'Software Quality', 'Evaluating software with accessibility checks, keyboard flows, screen readers, semantic markup, contrast, and issue reporting.'),
('advanced-specializations', 'Advanced Specializations', 'Career & Communication', 'Exploring advanced role-specific tracks while comparing prerequisites, learning depth, portfolio value, and career fit.'),
('ai-assisted-analysis', 'AI-Assisted Analysis', 'Data & Analytics', 'Using AI to explore data, generate hypotheses, summarize patterns, check assumptions, validate outputs, and support analyst workflows.'),
('airflow', 'Airflow', 'Data Engineering', 'Orchestrating data workflows with Airflow DAGs, tasks, schedules, dependencies, retries, backfills, and operational monitoring.'),
('analytics-case-interviews', 'Analytics Case Interviews', 'Data & Analytics', 'Analytics Case Interviews supports analytical work through metric definition, exploration, visualization, interpretation, validation, and communication of findings.'),
('analytics-engineering', 'Analytics Engineering', 'Data Engineering', 'Analytics Engineering supports data workflow reliability through ingestion, transformation, modeling, validation, orchestration, documentation, and lineage.'),
('analytics-lifecycle', 'Analytics Lifecycle', 'Data & Analytics', 'Analytics Lifecycle supports analytical work through metric definition, exploration, visualization, interpretation, validation, and communication of findings.'),
('android-development', 'Android Development', 'Mobile Development', 'Android Development supports mobile delivery through platform lifecycles, navigation, device APIs, local data, performance, accessibility, and release constraints.'),
('angular', 'Angular', 'Frontend', 'Building Angular applications with components, templates, services, routing, forms, dependency injection, and application structure.'),
('anomaly-detection', 'Anomaly Detection', 'AI & Machine Learning', 'Detecting unusual behavior with baselines, thresholds, outlier methods, time windows, alert signals, and model or rule-based techniques.'),
('ansible', 'Ansible', 'DevOps & Platform', 'Ansible supports delivery and operations through automation, deployment flow, observability, reliability practices, and platform maintenance.'),
('api', 'API', 'Backend', 'Designing and consuming APIs with endpoints, request and response contracts, authentication, validation, status codes, versioning, and error handling.'),
('api-client-design', 'API Client Design', 'Backend', 'Designing API clients with typed requests, response parsing, retries, cancellation, authentication, error handling, and integration boundaries.'),
('api-data-extraction', 'API Data Extraction', 'Data Engineering', 'Extracting data from APIs with authentication, pagination, rate limits, schema handling, retries, incremental loading, and error recovery.'),
('api-data-ingestion', 'API Data Ingestion', 'Data Engineering', 'Loading API data into reliable storage with extraction logic, scheduling, validation, schema checks, deduplication, and failure handling.'),
('api-security', 'API Security', 'Cybersecurity', 'API Security supports security work through threat awareness, access control, exposure reduction, validation, monitoring, and incident response.'),
('app-store-release', 'App Store Release', 'Mobile Development', 'App Store Release supports mobile delivery through platform lifecycles, navigation, device APIs, local data, performance, accessibility, and release constraints.'),
('appium-testing', 'Appium Testing', 'Software Quality', 'Defining test scope, scenarios, expected behavior, execution evidence, defect reporting, automation coverage, and release confidence.'),
('asynchronous-javascript', 'Asynchronous JavaScript', 'Programming', 'Asynchronous JavaScript develops coding ability through syntax, data structures, control flow, debugging, tooling, and maintainable implementation.'),
('authentication', 'Authentication', 'Cybersecurity', 'Verifying user or service identity through credentials, sessions, tokens, MFA, federation, and secure login flows.'),
('authorization', 'Authorization', 'Cybersecurity', 'Controlling access with roles, permissions, policies, scopes, ownership rules, and enforcement checks across application boundaries.'),
('aws', 'AWS', 'Cloud & Infrastructure', 'Using AWS services for identity, compute, storage, networking, databases, monitoring, automation, and cost-aware cloud operations.'),
('azure', 'Azure', 'Cloud & Infrastructure', 'Using Azure services for identity, compute, storage, networking, monitoring, deployment, governance, and cloud operations.'),
('backend-technology-selection', 'Backend Technology Selection', 'Backend', 'Comparing backend languages, frameworks, ecosystems, runtime constraints, team skills, deployment fit, and tradeoffs.'),
('bash', 'Bash', 'Systems & Operating Systems', 'Bash supports system-level work through files, processes, permissions, shells, services, logs, and troubleshooting tools.'),
('bias-and-fairness', 'Bias and Fairness', 'AI & Machine Learning', 'Bias and Fairness supports AI or ML work through data preparation, model behavior, evaluation, reliability, safety, and deployment tradeoffs.'),
('bigquery', 'BigQuery', 'Data & Analytics', 'Analyzing data in BigQuery with SQL, partitioning, clustering, warehouse storage, query cost awareness, and reporting workflows.'),
('bitbucket', 'Bitbucket', 'Tools & Workflow', 'Managing repositories, pull requests, branches, permissions, pipelines, and team collaboration workflows in Bitbucket.'),
('browser-storage', 'Browser Storage', 'Frontend', 'Using cookies, local storage, session storage, and IndexedDB while considering persistence, quota, serialization, security, and browser behavior.'),
('business-metrics', 'Business Metrics', 'Data & Analytics', 'Business Metrics supports analytical work through metric definition, exploration, visualization, interpretation, validation, and communication of findings.'),
('business-process-mapping', 'Business Process Mapping', 'Business & Product', 'Documenting business workflows, actors, handoffs, systems, decisions, and pain points so requirements can be improved or automated.'),
('capacity-planning', 'Capacity Planning', 'DevOps & Platform', 'Estimating workload demand, resource limits, growth trends, scaling thresholds, and operational headroom for reliable systems.'),
('career-planning', 'Career Planning', 'Career & Communication', 'Career Planning supports professional communication through technical evidence, tradeoff explanation, audience awareness, portfolio framing, and presentation.'),
('chart-selection', 'Chart Selection', 'Data & Analytics', 'Chart Selection supports analytical work through metric definition, exploration, visualization, interpretation, validation, and communication of findings.'),
('ci-cd', 'CI/CD', 'DevOps & Platform', 'CI/CD supports delivery and operations through automation, deployment flow, observability, reliability practices, and platform maintenance.'),
('client-side-routing', 'Client-Side Routing', 'Frontend', 'Implementing route definitions, navigation state, nested routes, parameters, redirects, guards, and browser history behavior.'),
('cloud-architecture', 'Cloud Architecture', 'Cloud & Infrastructure', 'Cloud Architecture supports infrastructure work through compute, storage, networking, hosting, scaling, reliability, security, and cost awareness.'),
('cloud-computing', 'Cloud Computing', 'Cloud & Infrastructure', 'Cloud Computing supports infrastructure work through compute, storage, networking, hosting, scaling, reliability, security, and cost awareness.'),
('cloud-cost-optimization', 'Cloud Cost Optimization', 'Cloud & Infrastructure', 'Cloud Cost Optimization supports infrastructure work through compute, storage, networking, hosting, scaling, reliability, security, and cost awareness.'),
('cloud-migration', 'Cloud Migration', 'Cloud & Infrastructure', 'Cloud Migration supports infrastructure work through compute, storage, networking, hosting, scaling, reliability, security, and cost awareness.'),
('cloud-monitoring', 'Cloud Monitoring', 'Cloud & Infrastructure', 'Cloud Monitoring supports infrastructure work through compute, storage, networking, hosting, scaling, reliability, security, and cost awareness.'),
('cloud-networking', 'Cloud Networking', 'Cloud & Infrastructure', 'Cloud Networking supports infrastructure work through compute, storage, networking, hosting, scaling, reliability, security, and cost awareness.'),
('cloud-security', 'Cloud Security', 'Cybersecurity', 'Cloud Security supports security work through threat awareness, access control, exposure reduction, validation, monitoring, and incident response.'),
('cloud-storage', 'Cloud Storage', 'Cloud & Infrastructure', 'Cloud Storage supports infrastructure work through compute, storage, networking, hosting, scaling, reliability, security, and cost awareness.'),
('clustering', 'Clustering', 'AI & Machine Learning', 'Clustering supports AI or ML work through data preparation, model behavior, evaluation, reliability, safety, and deployment tradeoffs.'),
('cohort-analysis', 'Cohort Analysis', 'Data & Analytics', 'Cohort Analysis supports analytical work through metric definition, exploration, visualization, interpretation, validation, and communication of findings.'),
('command-line', 'Command Line', 'Tools & Workflow', 'Command Line supports development workflow through setup, collaboration, automation, documentation, repeatability, and delivery handoff.'),
('community-management', 'Community Management', 'Career & Communication', 'Community Management supports professional communication through technical evidence, tradeoff explanation, audience awareness, portfolio framing, and presentation.'),
('confidence-intervals', 'Confidence Intervals', 'Mathematics & Theory', 'Confidence Intervals supports formal reasoning through definitions, assumptions, formulas, algorithms, proofs, and quantitative tradeoffs.'),
('configuration-management', 'Configuration Management', 'DevOps & Platform', 'Configuration Management supports delivery and operations through automation, deployment flow, observability, reliability practices, and platform maintenance.'),
('containerization', 'Containerization', 'DevOps & Platform', 'Containerization supports delivery and operations through automation, deployment flow, observability, reliability practices, and platform maintenance.'),
('core-web-vitals', 'Core Web Vitals', 'Frontend', 'Core Web Vitals supports web interface development through components, browser behavior, layout, state, accessibility, and performance considerations.'),
('correlation-vs-causation', 'Correlation vs Causation', 'Data & Analytics', 'Correlation vs Causation supports analytical work through metric definition, exploration, visualization, interpretation, validation, and communication of findings.'),
('cplusplus-for-unreal-and-engine-systems', 'C++ for Unreal and Engine Systems', 'Game Development', 'C++ for Unreal and Engine Systems supports game production through engine workflow, runtime behavior, assets, player interaction, simulation, and performance constraints.'),
('csharp', 'C#', 'Programming', 'Writing C# applications with types, classes, LINQ, async patterns, error handling, tooling, and maintainable object-oriented structure.'),
('csharp-for-unity-gameplay', 'C# for Unity Gameplay', 'Game Development', 'C# for Unity Gameplay supports game production through engine workflow, runtime behavior, assets, player interaction, simulation, and performance constraints.'),
('css', 'CSS', 'Frontend', 'Styling web interfaces with selectors, cascade, specificity, box model, layout systems, responsive behavior, and maintainable style organization.'),
('cypress', 'Cypress', 'Software Quality', 'Configuring Cypress projects with the test runner, selectors, fixtures, network stubbing, debugging tools, and CI execution.'),
('cypress-testing', 'Cypress Testing', 'Software Quality', 'Writing Cypress end-to-end and component tests with assertions, fixtures, selectors, user flows, and browser automation.'),
('dart', 'Dart', 'Mobile Development', 'Writing Dart code for Flutter applications with null safety, asynchronous programming, collections, classes, packages, and UI-oriented patterns.'),
('dashboard-design', 'Dashboard Design', 'Data & Analytics', 'Designing dashboards around user goals, metric hierarchy, layout, chart choice, filters, annotations, and decision-making flow.'),
('dashboard-documentation', 'Dashboard Documentation', 'Tools & Workflow', 'Dashboard Documentation supports development workflow through setup, collaboration, automation, documentation, repeatability, and delivery handoff.'),
('dashboard-performance', 'Dashboard Performance', 'Data & Analytics', 'Improving dashboard speed through query tuning, model design, aggregation, caching, extract strategy, and visual simplification.'),
('dashboard-quality-assurance', 'Dashboard Quality Assurance', 'Software Quality', 'Dashboard Quality Assurance supports software quality through test design, expected behavior, defect evidence, automation scope, risk coverage, and release confidence.'),
('data-catalogs', 'Data Catalogs', 'Data Engineering', 'Data Catalogs supports data workflow reliability through ingestion, transformation, modeling, validation, orchestration, documentation, and lineage.'),
('data-cleaning', 'Data Cleaning', 'Data & Analytics', 'Preparing data by fixing missing values, duplicates, formats, outliers, invalid records, inconsistent categories, and quality issues.'),
('data-contracts', 'Data Contracts', 'Data Engineering', 'Data Contracts supports data workflow reliability through ingestion, transformation, modeling, validation, orchestration, documentation, and lineage.'),
('data-governance', 'Data Governance', 'Data Engineering', 'Data Governance supports data workflow reliability through ingestion, transformation, modeling, validation, orchestration, documentation, and lineage.'),
('data-lineage', 'Data Lineage', 'Data Engineering', 'Data Lineage supports data workflow reliability through ingestion, transformation, modeling, validation, orchestration, documentation, and lineage.'),
('data-literacy', 'Data Literacy', 'Data & Analytics', 'Data Literacy supports analytical work through metric definition, exploration, visualization, interpretation, validation, and communication of findings.'),
('data-modeling', 'Data Modeling', 'Database', 'Data Modeling supports data storage and querying through schemas, relationships, constraints, indexes, transactions, and performance reasoning.'),
('data-profiling', 'Data Profiling', 'Data & Analytics', 'Data Profiling supports analytical work through metric definition, exploration, visualization, interpretation, validation, and communication of findings.'),
('data-quality', 'Data Quality', 'Data & Analytics', 'Data Quality supports analytical work through metric definition, exploration, visualization, interpretation, validation, and communication of findings.'),
('data-quality-dimensions', 'Data Quality Dimensions', 'Data & Analytics', 'Data Quality Dimensions supports analytical work through metric definition, exploration, visualization, interpretation, validation, and communication of findings.'),
('data-storytelling', 'Data Storytelling', 'Data & Analytics', 'Data Storytelling supports analytical work through metric definition, exploration, visualization, interpretation, validation, and communication of findings.'),
('data-tests', 'Data Tests', 'Data Engineering', 'Data Tests supports data workflow reliability through ingestion, transformation, modeling, validation, orchestration, documentation, and lineage.'),
('data-validation', 'Data Validation', 'Data & Analytics', 'Data Validation supports analytical work through metric definition, exploration, visualization, interpretation, validation, and communication of findings.'),
('data-visualization', 'Data Visualization', 'Data & Analytics', 'Data Visualization supports analytical work through metric definition, exploration, visualization, interpretation, validation, and communication of findings.'),
('dbt', 'dbt', 'Data Engineering', 'Building dbt projects with models, sources, tests, documentation, materializations, dependencies, and deployment jobs.'),
('deep-learning-and-neural-networks', 'Deep Learning and Neural Networks', 'AI & Machine Learning', 'Deep Learning and Neural Networks supports AI or ML work through data preparation, model behavior, evaluation, reliability, safety, and deployment tradeoffs.'),
('descriptive-statistics', 'Descriptive Statistics', 'Mathematics & Theory', 'Descriptive Statistics supports formal reasoning through definitions, assumptions, formulas, algorithms, proofs, and quantitative tradeoffs.'),
('design-tokens-and-theming', 'Design Tokens and Theming', 'Design & UX', 'Defining reusable color, spacing, typography, radius, motion, and theme tokens that keep interfaces visually consistent.'),
('detox-for-react-native', 'Detox for React Native', 'Frontend', 'Detox for React Native supports web interface development through components, browser behavior, layout, state, accessibility, and performance considerations.'),
('devops', 'DevOps', 'DevOps & Platform', 'DevOps supports delivery and operations through automation, deployment flow, observability, reliability practices, and platform maintenance.'),
('distributions-and-sampling', 'Distributions and Sampling', 'Mathematics & Theory', 'Distributions and Sampling supports formal reasoning through definitions, assumptions, formulas, algorithms, proofs, and quantitative tradeoffs.'),
('django', 'Django', 'Backend', 'Building backend web applications with Django models, views, routing, forms, authentication, admin tools, and deployment practices.'),
('dns', 'DNS', 'Networking', 'DNS supports network work through addressing, protocols, topology, forwarding behavior, configuration, and troubleshooting evidence.'),
('docker', 'Docker', 'DevOps & Platform', 'Packaging applications with Docker images, Dockerfiles, containers, volumes, networks, registries, and reproducible runtime configuration.'),
('end-to-end-type-safety', 'End-to-End Type Safety', 'Software Quality', 'Maintaining type guarantees across frontend, backend, API contracts, validation schemas, and generated client code.'),
('environment-management', 'Environment Management', 'Tools & Workflow', 'Environment Management supports development workflow through setup, collaboration, automation, documentation, repeatability, and delivery handoff.'),
('error-analysis', 'Error Analysis', 'Data & Analytics', 'Error Analysis supports analytical work through metric definition, exploration, visualization, interpretation, validation, and communication of findings.'),
('error-handling-and-logging', 'Error Handling and Logging', 'DevOps & Platform', 'Error Handling and Logging supports delivery and operations through automation, deployment flow, observability, reliability practices, and platform maintenance.'),
('eslint-and-prettier', 'ESLint and Prettier', 'Tools & Workflow', 'ESLint and Prettier supports development workflow through setup, collaboration, automation, documentation, repeatability, and delivery handoff.'),
('etl-vs-elt', 'ETL vs ELT', 'Data Engineering', 'ETL vs ELT supports data workflow reliability through ingestion, transformation, modeling, validation, orchestration, documentation, and lineage.'),
('evaluation-metrics', 'Evaluation Metrics', 'Data & Analytics', 'Evaluation Metrics supports analytical work through metric definition, exploration, visualization, interpretation, validation, and communication of findings.'),
('excel', 'Excel', 'Data & Analytics', 'Excel supports analytical work through metric definition, exploration, visualization, interpretation, validation, and communication of findings.'),
('executive-summary-writing', 'Executive Summary Writing', 'Career & Communication', 'Executive Summary Writing supports professional communication through technical evidence, tradeoff explanation, audience awareness, portfolio framing, and presentation.'),
('experiment-tracking', 'Experiment Tracking', 'Data & Analytics', 'Experiment Tracking supports analytical work through metric definition, exploration, visualization, interpretation, validation, and communication of findings.'),
('exploratory-data-analysis', 'Exploratory Data Analysis', 'Data & Analytics', 'Exploratory Data Analysis supports analytical work through metric definition, exploration, visualization, interpretation, validation, and communication of findings.'),
('exploratory-testing', 'Exploratory Testing', 'Software Quality', 'Investigating software behavior without rigid scripts to discover unexpected risks, edge cases, defects, and usability issues.'),
('feature-engineering', 'Feature Engineering', 'AI & Machine Learning', 'Feature Engineering supports AI or ML work through data preparation, model behavior, evaluation, reliability, safety, and deployment tradeoffs.'),
('firebase', 'Firebase', 'Cloud & Infrastructure', 'Firebase supports infrastructure work through compute, storage, networking, hosting, scaling, reliability, security, and cost awareness.'),
('flutter', 'Flutter', 'Mobile Development', 'Flutter supports mobile delivery through platform lifecycles, navigation, device APIs, local data, performance, accessibility, and release constraints.'),
('frontend-backend-integration', 'Frontend-Backend Integration', 'Frontend', 'Frontend-Backend Integration supports web interface development through components, browser behavior, layout, state, accessibility, and performance considerations.'),
('frontend-performance', 'Frontend Performance', 'Frontend', 'Frontend Performance supports web interface development through components, browser behavior, layout, state, accessibility, and performance considerations.'),
('full-stack-development', 'Full Stack Development', 'Programming', 'Full Stack Development develops coding ability through syntax, data structures, control flow, debugging, tooling, and maintainable implementation.'),
('full-stack-testing', 'Full Stack Testing', 'Software Quality', 'Testing complete application flows across frontend, backend, database, authentication, integrations, and deployment environments.'),
('funnel-analysis', 'Funnel Analysis', 'Data & Analytics', 'Funnel Analysis supports analytical work through metric definition, exploration, visualization, interpretation, validation, and communication of findings.'),
('gdscript-for-godot', 'GDScript for Godot', 'Game Development', 'GDScript for Godot supports game production through engine workflow, runtime behavior, assets, player interaction, simulation, and performance constraints.'),
('git', 'Git', 'Tools & Workflow', 'Managing source history with commits, branches, merges, rebases, tags, conflict resolution, and collaborative repository workflows.'),
('github', 'GitHub', 'Tools & Workflow', 'Collaborating on GitHub with repositories, pull requests, issues, reviews, Actions workflows, permissions, and project documentation.'),
('gitlab', 'GitLab', 'Tools & Workflow', 'GitLab supports development workflow through setup, collaboration, automation, documentation, repeatability, and delivery handoff.'),
('gitops', 'GitOps', 'DevOps & Platform', 'GitOps supports delivery and operations through automation, deployment flow, observability, reliability practices, and platform maintenance.'),
('go', 'Go', 'Programming', 'Writing Go programs with modules, types, interfaces, goroutines, channels, HTTP services, and command-line tooling.'),
('godot-engine', 'Godot Engine', 'Game Development', 'Godot Engine supports game production through engine workflow, runtime behavior, assets, player interaction, simulation, and performance constraints.'),
('google-cloud', 'Google Cloud', 'Cloud & Infrastructure', 'Google Cloud supports infrastructure work through compute, storage, networking, hosting, scaling, reliability, security, and cost awareness.'),
('governance-and-guardrails', 'Governance and Guardrails', 'Cybersecurity', 'Governance and Guardrails supports security work through threat awareness, access control, exposure reduction, validation, monitoring, and incident response.'),
('gradient-boosting', 'Gradient Boosting', 'AI & Machine Learning', 'Gradient Boosting supports AI or ML work through data preparation, model behavior, evaluation, reliability, safety, and deployment tradeoffs.'),
('grafana-k6', 'Grafana K6', 'DevOps & Platform', 'Grafana K6 supports delivery and operations through automation, deployment flow, observability, reliability practices, and platform maintenance.'),
('graphql', 'GraphQL', 'Backend', 'GraphQL supports server-side development through API behavior, service boundaries, data access, validation, reliability, and integration concerns.'),
('helm', 'Helm', 'DevOps & Platform', 'Helm supports delivery and operations through automation, deployment flow, observability, reliability practices, and platform maintenance.'),
('html', 'HTML', 'Frontend', 'HTML supports web interface development through components, browser behavior, layout, state, accessibility, and performance considerations.'),
('http', 'HTTP', 'Web', 'HTTP is a reusable competency with clear concepts, practical application, validation, and learning-module relevance.'),
('hypothesis-testing', 'Hypothesis Testing', 'Software Quality', 'Defining test scope, scenarios, expected behavior, execution evidence, defect reporting, automation coverage, and release confidence.'),
('iam', 'Identity and Access Management', 'Cybersecurity', 'Identity and Access Management supports security work through threat awareness, access control, exposure reduction, validation, monitoring, and incident response.'),
('incident-response', 'Incident Response', 'Cybersecurity', 'Handling incidents with detection, triage, containment, communication, remediation, post-incident review, and prevention follow-up.'),
('infrastructure-as-code', 'Infrastructure As Code', 'Cloud & Infrastructure', 'Infrastructure As Code supports infrastructure work through compute, storage, networking, hosting, scaling, reliability, security, and cost awareness.'),
('internet', 'Internet', 'Networking', 'Understanding internet communication through IP addressing, DNS, routing, HTTP, TLS, service boundaries, and troubleshooting signals.'),
('interview-readiness', 'Interview Readiness', 'Career & Communication', 'Preparing for interviews with role expectations, technical explanations, practice problems, project stories, and concise communication.'),
('ios-development', 'iOS Development', 'Mobile Development', 'iOS Development supports mobile delivery through platform lifecycles, navigation, device APIs, local data, performance, accessibility, and release constraints.'),
('ip-addressing-and-subnetting', 'IP Addressing and Subnetting', 'Networking', 'IP Addressing and Subnetting supports network work through addressing, protocols, topology, forwarding behavior, configuration, and troubleshooting evidence.'),
('java', 'Java', 'Programming', 'Writing Java applications with classes, interfaces, collections, exceptions, generics, build tools, concurrency basics, and runtime behavior.'),
('javascript', 'JavaScript', 'Programming', 'Writing JavaScript with functions, objects, modules, asynchronous behavior, browser APIs, error handling, and maintainable structure.'),
('jest-and-vitest', 'Jest and Vitest', 'Software Quality', 'Testing JavaScript and TypeScript code with assertions, mocks, fixtures, snapshots, coverage, and continuous integration.'),
('jwt', 'JWT', 'Cybersecurity', 'Using JWTs with claims, signing, expiration, validation, storage risks, and authorization boundaries.'),
('kafka', 'Kafka', 'DevOps & Platform', 'Kafka supports delivery and operations through automation, deployment flow, observability, reliability practices, and platform maintenance.'),
('kotlin', 'Kotlin', 'Programming', 'Kotlin develops coding ability through syntax, data structures, control flow, debugging, tooling, and maintainable implementation.'),
('kubernetes', 'Kubernetes', 'DevOps & Platform', 'Operating Kubernetes workloads with pods, deployments, services, config, secrets, ingress, scaling, updates, and cluster troubleshooting.'),
('linux', 'Linux', 'Systems & Operating Systems', 'Administering Linux systems through the shell, filesystems, permissions, processes, services, networking tools, and logs.'),
('load-balancing', 'Load Balancing', 'Networking', 'Load Balancing supports network work through addressing, protocols, topology, forwarding behavior, configuration, and troubleshooting evidence.'),
('looker', 'Looker', 'Data & Analytics', 'Looker supports analytical work through metric definition, exploration, visualization, interpretation, validation, and communication of findings.'),
('looker-and-looker-studio', 'Looker and Looker Studio', 'Data & Analytics', 'Using Looker semantic modeling and Looker Studio reporting to define governed metrics and deliver interactive analytics.'),
('looker-studio', 'Looker Studio', 'Data & Analytics', 'Creating Looker Studio reports with data sources, calculated fields, filters, charts, sharing, and dashboard maintenance.'),
('loss-functions', 'Loss Functions', 'AI & Machine Learning', 'Loss Functions supports AI or ML work through data preparation, model behavior, evaluation, reliability, safety, and deployment tradeoffs.'),
('maestro-mobile-testing', 'Maestro Mobile Testing', 'Software Quality', 'Automating mobile test flows with Maestro commands, selectors, assertions, device actions, test data, and CI-friendly execution.'),
('metrics', 'Metrics', 'Data & Analytics', 'Defining reliable measures with clear formulas, grain, filters, owners, interpretation notes, and decision context.'),
('mobile-accessibility', 'Mobile Accessibility', 'Mobile Development', 'Making mobile interfaces usable with screen readers, focus order, touch targets, contrast, dynamic type, and platform accessibility APIs.'),
('mobile-development', 'Mobile Development', 'Mobile Development', 'Building mobile applications with platform lifecycles, navigation, device APIs, local storage, performance, accessibility, and release workflows.'),
('mobile-performance', 'Mobile Performance', 'Mobile Development', 'Improving mobile responsiveness, startup time, memory use, network behavior, battery usage, rendering, and crash stability.'),
('mobile-security', 'Mobile Security', 'Cybersecurity', 'Protecting mobile apps with secure storage, transport security, authentication, permissions, dependency hygiene, and tamper awareness.'),
('mobile-testing', 'Mobile Testing', 'Software Quality', 'Testing mobile behavior across devices, OS versions, permissions, network conditions, gestures, notifications, and app lifecycle events.'),
('mobile-ui-ux', 'Mobile UI/UX', 'Mobile Development', 'Designing mobile experiences with touch targets, navigation patterns, gestures, responsiveness, accessibility, and platform expectations.'),
('model-evaluation', 'Model Evaluation', 'AI & Machine Learning', 'Working with model evaluation through inputs, behavior, evaluation criteria, limitations, deployment constraints, and monitoring signals.'),
('model-registry', 'Model Registry', 'DevOps & Platform', 'Model Registry supports delivery and operations through automation, deployment flow, observability, reliability practices, and platform maintenance.'),
('model-selection', 'Model Selection', 'AI & Machine Learning', 'Working with model selection through inputs, behavior, evaluation criteria, limitations, deployment constraints, and monitoring signals.'),
('model-validation', 'Model Validation', 'AI & Machine Learning', 'Working with model validation through inputs, behavior, evaluation criteria, limitations, deployment constraints, and monitoring signals.'),
('mongodb', 'MongoDB', 'Database', 'MongoDB supports data storage and querying through schemas, relationships, constraints, indexes, transactions, and performance reasoning.'),
('monitoring', 'Monitoring', 'DevOps & Platform', 'Monitoring supports delivery and operations through automation, deployment flow, observability, reliability practices, and platform maintenance.'),
('mysql', 'MySQL', 'Database', 'Working with MySQL schemas, SQL queries, indexes, joins, transactions, constraints, replication basics, and performance tuning.'),
('networking', 'Networking', 'Networking', 'Designing and troubleshooting connected systems with addressing, routing, switching, protocols, segmentation, and operational diagnostics.'),
('networking-fundamentals', 'Networking Fundamentals', 'Networking', 'Understanding OSI and TCP/IP concepts, addressing, routing, DNS, switching, wireless basics, and troubleshooting workflows.'),
('next-js', 'Next.js', 'Frontend', 'Building Next.js applications with file-based routing, layouts, rendering modes, data fetching, API routes, caching, and deployment.'),
('nginx', 'Nginx', 'Cloud & Infrastructure', 'Nginx supports infrastructure work through compute, storage, networking, hosting, scaling, reliability, security, and cost awareness.'),
('node-js-and-express', 'Node.js and Express', 'Backend', 'Building backend services with Node.js and Express routing, middleware, request validation, controllers, errors, and deployment behavior.'),
('nosql', 'NoSQL', 'Database', 'NoSQL supports data storage and querying through schemas, relationships, constraints, indexes, transactions, and performance reasoning.'),
('npm', 'npm', 'Tools & Workflow', 'Managing JavaScript packages with npm scripts, dependencies, lockfiles, semantic versioning, registries, and install workflows.'),
('nuxt-js', 'Nuxt.js', 'Frontend', 'Building Vue-based applications with Nuxt routing, server rendering, data fetching, layouts, modules, and deployment options.'),
('oauth', 'OAuth', 'Cybersecurity', 'Implementing OAuth flows with clients, authorization grants, redirects, scopes, tokens, refresh behavior, and secure callback handling.'),
('observability', 'Observability', 'DevOps & Platform', 'Observability supports delivery and operations through automation, deployment flow, observability, reliability practices, and platform maintenance.'),
('observer-pattern-and-reactive-ui', 'Observer Pattern and Reactive UI', 'Frontend', 'Coordinating UI updates with observable state, subscriptions, event streams, dependency tracking, and reactive rendering behavior.'),
('offline-first', 'Offline-First Apps', 'Mobile Development', 'Designing apps that continue working with local data, sync queues, conflict handling, retries, and network recovery.'),
('offline-vs-online-evaluation', 'Offline vs Online Evaluation', 'AI & Machine Learning', 'Offline vs Online Evaluation supports AI or ML work through data preparation, model behavior, evaluation, reliability, safety, and deployment tradeoffs.'),
('pandas', 'pandas', 'Data & Analytics', 'pandas supports analytical work through metric definition, exploration, visualization, interpretation, validation, and communication of findings.'),
('pandas-data-analysis', 'pandas Data Analysis', 'Data & Analytics', 'pandas Data Analysis supports analytical work through metric definition, exploration, visualization, interpretation, validation, and communication of findings.'),
('pandas-dataframes', 'pandas DataFrames', 'Data & Analytics', 'pandas DataFrames supports analytical work through metric definition, exploration, visualization, interpretation, validation, and communication of findings.'),
('performance-analysis', 'Performance Analysis', 'Data & Analytics', 'Measuring performance with benchmarks, profiling, bottleneck investigation, baseline comparison, and improvement validation.'),
('php', 'PHP', 'Programming', 'Writing PHP applications with syntax, arrays, functions, classes, HTTP handling, package management, and server-side templates.'),
('pii-and-sensitive-data', 'PII and Sensitive Data', 'Cybersecurity', 'PII and Sensitive Data supports security work through threat awareness, access control, exposure reduction, validation, monitoring, and incident response.'),
('platform-engineering', 'Platform Engineering', 'DevOps & Platform', 'Platform Engineering supports delivery and operations through automation, deployment flow, observability, reliability practices, and platform maintenance.'),
('playwright', 'Playwright', 'Software Quality', 'Using Playwright for browser automation with contexts, pages, locators, traces, screenshots, and cross-browser execution.'),
('playwright-testing', 'Playwright Testing', 'Software Quality', 'Writing Playwright tests with robust locators, assertions, fixtures, parallel execution, tracing, and CI reports.'),
('pnpm', 'pnpm', 'Tools & Workflow', 'Managing JavaScript workspaces and dependencies with pnpm lockfiles, stores, scripts, workspace filters, and reproducible installs.'),
('portfolio-communication', 'Portfolio Communication', 'Career & Communication', 'Presenting project work with problem context, technical decisions, evidence, screenshots, outcomes, and clear learner reflection.'),
('postgresql', 'PostgreSQL', 'Database', 'Working with PostgreSQL databases through schemas, SQL queries, indexes, transactions, constraints, and operational tuning.'),
('postman', 'Postman', 'Tools & Workflow', 'Postman supports development workflow through setup, collaboration, automation, documentation, repeatability, and delivery handoff.'),
('postman-newman-cli', 'Postman Newman CLI', 'Tools & Workflow', 'Postman Newman CLI supports development workflow through setup, collaboration, automation, documentation, repeatability, and delivery handoff.'),
('power-bi', 'Power BI', 'Data & Analytics', 'Building Power BI reports with data models, DAX measures, visuals, filters, refresh configuration, and sharing practices.'),
('power-query', 'Power Query', 'Data & Analytics', 'Transforming BI data with Power Query steps, joins, pivots, type changes, parameters, refresh behavior, and reusable cleaning logic.'),
('privacy-and-data-protection', 'Privacy and Data Protection', 'Cybersecurity', 'Protecting personal data through minimization, consent, retention rules, access controls, encryption, and compliance-aware handling.'),
('production-web-deployment', 'Production Web Deployment', 'DevOps & Platform', 'Production Web Deployment supports delivery and operations through automation, deployment flow, observability, reliability practices, and platform maintenance.'),
('prompt-injection', 'Prompt Injection', 'AI & Machine Learning', 'Prompt Injection supports AI or ML work through data preparation, model behavior, evaluation, reliability, safety, and deployment tradeoffs.'),
('python', 'Python', 'Programming', 'Writing Python programs with data structures, functions, modules, virtual environments, file handling, exceptions, packages, and testing basics.'),
('python-syntax-and-control-flow', 'Python Syntax and Control Flow', 'Programming', 'Writing Python basics with variables, conditionals, loops, functions, exceptions, modules, and simple data structures.'),
('python-visualization', 'Python Visualization', 'Data & Analytics', 'Python Visualization supports analytical work through metric definition, exploration, visualization, interpretation, validation, and communication of findings.'),
('pytorch', 'PyTorch', 'AI & Machine Learning', 'Building neural network workflows in PyTorch with tensors, modules, autograd, datasets, optimizers, training loops, and checkpoints.'),
('quality-monitoring', 'Quality Monitoring', 'Software Quality', 'Quality Monitoring supports software quality through test design, expected behavior, defect evidence, automation scope, risk coverage, and release confidence.'),
('query-optimization', 'Query Optimization', 'Database', 'Improving database queries through indexing, execution plans, join strategies, statistics, and measurement of runtime behavior.'),
('rabbitmq', 'RabbitMQ', 'Backend', 'RabbitMQ supports server-side development through API behavior, service boundaries, data access, validation, reliability, and integration concerns.'),
('react', 'React', 'Frontend', 'Building React interfaces with components, props, state, hooks, rendering behavior, routing integration, and reusable UI patterns.'),
('react-components-and-props', 'React Components and Props', 'Frontend', 'Creating React components with props, composition, conditional rendering, event handling, and reusable UI boundaries.'),
('react-core-architecture', 'React Core Architecture', 'Frontend', 'Organizing React applications with component boundaries, state ownership, data flow, routing, and maintainable feature structure.'),
('react-error-boundaries-and-fallback-ui', 'React Error Boundaries and Fallback UI', 'Frontend', 'Handling React rendering failures with error boundaries, fallback screens, recovery paths, and user-safe failure states.'),
('react-hooks-and-effects', 'React Hooks and Effects', 'Frontend', 'Managing React state and side effects with hooks, dependency arrays, cleanup functions, memoization, and component lifecycle behavior.'),
('react-native', 'React Native', 'Frontend', 'React Native supports web interface development through components, browser behavior, layout, state, accessibility, and performance considerations.'),
('react-routing-and-layouts', 'React Routing and Layouts', 'Frontend', 'Structuring React applications with route definitions, nested layouts, URL parameters, navigation state, and protected pages.'),
('recommendation-systems', 'Recommendation Systems', 'AI & Machine Learning', 'Building recommenders with user/item signals, candidate generation, ranking, evaluation metrics, feedback loops, and bias considerations.'),
('redis', 'Redis', 'Database', 'Using Redis for key-value caching, data structures, expiration, pub/sub, persistence tradeoffs, and performance-sensitive access.'),
('relational-databases', 'Relational Databases', 'Database', 'Modeling structured data with tables, relationships, keys, constraints, normalization, transactions, and SQL queries.'),
('release-management', 'Release Management', 'DevOps & Platform', 'Release Management supports delivery and operations through automation, deployment flow, observability, reliability practices, and platform maintenance.'),
('release-readiness', 'Release Readiness', 'Software Quality', 'Checking whether a release has acceptable quality evidence, known risks, rollback plans, approvals, and monitoring coverage.'),
('reproducible-experiments', 'Reproducible Experiments', 'AI & Machine Learning', 'Reproducible Experiments supports AI or ML work through data preparation, model behavior, evaluation, reliability, safety, and deployment tradeoffs.'),
('requirements-analysis', 'Requirements Analysis', 'Business & Product', 'Requirements Analysis supports product work through stakeholder needs, workflows, constraints, priorities, business rules, and measurable outcomes.'),
('responsible-ai-and-governance', 'Responsible AI and Governance', 'AI & Machine Learning', 'Managing AI systems with safety practices, fairness checks, documentation, policy constraints, monitoring, review processes, and accountability.'),
('responsive-design', 'Responsive Design', 'Frontend', 'Building layouts that adapt across screen sizes with fluid grids, breakpoints, flexible media, typography, and input constraints.'),
('rest-apis', 'REST APIs', 'Backend', 'REST APIs supports server-side development through API behavior, service boundaries, data access, validation, reliability, and integration concerns.'),
('retention-analysis', 'Retention Analysis', 'Data & Analytics', 'Measuring how users continue, return, churn, or re-engage across cohorts, segments, and lifecycle periods.'),
('reverse-proxies', 'Reverse Proxies', 'Cloud & Infrastructure', 'Reverse Proxies supports infrastructure work through compute, storage, networking, hosting, scaling, reliability, security, and cost awareness.'),
('ruby', 'Ruby', 'Programming', 'Writing Ruby programs with objects, blocks, modules, collections, exceptions, gems, and maintainable idioms.'),
('rust', 'Rust', 'Programming', 'Writing Rust programs with ownership, borrowing, lifetimes, traits, pattern matching, error handling, and Cargo workflows.'),
('secrets-management', 'Secrets Management', 'Cybersecurity', 'Protecting secrets with secure storage, rotation, access controls, environment isolation, scanning, and audit practices.'),
('secure-web-application-development', 'Secure Web Application Development', 'Cybersecurity', 'Building web apps with input validation, authentication, authorization, secure session handling, dependency hygiene, and attack mitigation.'),
('security-headers-and-csp', 'Security Headers and CSP', 'Cybersecurity', 'Configuring browser security headers and Content Security Policy to reduce injection, framing, MIME, and data exposure risks.'),
('select-filtering-and-sorting', 'SELECT, Filtering, and Sorting', 'Database', 'Writing SQL queries that select columns, filter rows, sort results, limit output, and validate returned data.'),
('selenium-webdriver', 'Selenium WebDriver', 'Software Quality', 'Selenium WebDriver supports software quality through test design, expected behavior, defect evidence, automation scope, risk coverage, and release confidence.'),
('semantic-layer', 'Semantic Layer', 'Data & Analytics', 'Defining governed business metrics, dimensions, relationships, access rules, and reusable analytical definitions across tools.'),
('serverless', 'Serverless', 'Cloud & Infrastructure', 'Building event-driven workloads with functions, triggers, managed scaling, cold starts, permissions, observability, and cost behavior.'),
('slowly-changing-dimensions', 'Slowly Changing Dimensions', 'Data Engineering', 'Modeling historical dimension changes with type strategies, effective dates, surrogate keys, current flags, and auditability.'),
('snowflake', 'Snowflake', 'Data Engineering', 'Working with Snowflake warehouses, databases, schemas, roles, stages, SQL transformations, scaling, and cost controls.'),
('spark', 'Spark', 'Data Engineering', 'Spark supports data workflow reliability through ingestion, transformation, modeling, validation, orchestration, documentation, and lineage.'),
('spreadsheet-data-cleaning', 'Spreadsheet Data Cleaning', 'Data & Analytics', 'Cleaning spreadsheet data with consistent formats, formulas, validation, deduplication, missing-value handling, and audit-friendly edits.'),
('spreadsheets', 'Spreadsheets', 'Data & Analytics', 'Using spreadsheets for tabular analysis, formulas, pivots, charts, validation, collaboration, and lightweight reporting.'),
('sql', 'SQL', 'Database', 'Writing SQL queries with selection, filtering, joins, grouping, subqueries, window functions, aggregation, and result validation.'),
('sqlite', 'SQLite', 'Database', 'Using SQLite for embedded relational storage with tables, SQL queries, transactions, indexes, constraints, and local application data.'),
('sre-practices', 'SRE Practices', 'DevOps & Platform', 'SRE Practices supports delivery and operations through automation, deployment flow, observability, reliability practices, and platform maintenance.'),
('stakeholder-communication', 'Stakeholder Communication', 'Career & Communication', 'Communicating with stakeholders through clear questions, status updates, risks, tradeoffs, decisions, and audience-aware summaries.'),
('statistics', 'Statistics', 'Mathematics & Theory', 'Statistics supports formal reasoning through definitions, assumptions, formulas, algorithms, proofs, and quantitative tradeoffs.'),
('survey-analysis', 'Survey Analysis', 'Data & Analytics', 'Analyzing survey data with question design awareness, response cleaning, segmentation, bias checks, and summarized findings.'),
('swift', 'Swift', 'Programming', 'Writing Swift code with optionals, structs, classes, protocols, closures, concurrency, package management, and iOS-oriented patterns.'),
('tableau', 'Tableau', 'Data & Analytics', 'Tableau supports analytical work through metric definition, exploration, visualization, interpretation, validation, and communication of findings.'),
('technical-case-studies', 'Technical Case Studies', 'Career & Communication', 'Writing case studies that explain problem context, constraints, decisions, implementation evidence, results, and lessons learned.'),
('tensorflow', 'TensorFlow', 'AI & Machine Learning', 'Building machine learning workflows in TensorFlow with tensors, layers, datasets, graph execution, training loops, and saved models.'),
('tensorflow-and-keras', 'TensorFlow and Keras', 'AI & Machine Learning', 'Building neural networks with TensorFlow and Keras layers, models, callbacks, optimizers, losses, metrics, and checkpoints.'),
('terraform', 'Terraform', 'DevOps & Platform', 'Terraform supports delivery and operations through automation, deployment flow, observability, reliability practices, and platform maintenance.'),
('testing', 'Testing', 'Software Quality', 'Designing tests across levels with expected behavior, test data, assertions, defect evidence, automation scope, and release confidence.'),
('time-series-analysis', 'Time Series Analysis', 'Data & Analytics', 'Time Series Analysis supports analytical work through metric definition, exploration, visualization, interpretation, validation, and communication of findings.'),
('training-loops', 'Training Loops', 'AI & Machine Learning', 'Training Loops supports AI or ML work through data preparation, model behavior, evaluation, reliability, safety, and deployment tradeoffs.'),
('typescript', 'TypeScript', 'Programming', 'Writing TypeScript with static types, interfaces, generics, narrowing, modules, compiler checks, and maintainable JavaScript integration.'),
('unity-engine', 'Unity Engine', 'Game Development', 'Building games in Unity with scenes, GameObjects, components, prefabs, physics, animation, scripting, and build settings.'),
('unity-netcode-or-mirror', 'Unity Netcode or Mirror', 'Game Development', 'Building Unity multiplayer features with networked objects, authority, synchronization, RPCs, prediction limits, and connection handling.'),
('unreal-engine', 'Unreal Engine', 'Game Development', 'Building games in Unreal with actors, components, Blueprints, C++ classes, levels, materials, and packaging workflow.'),
('unreal-replication', 'Unreal Replication', 'Game Development', 'Synchronizing Unreal multiplayer state with replicated properties, RPCs, ownership, relevancy, authority, and bandwidth constraints.'),
('version-control-for-analysis', 'Version Control for Analysis', 'Data & Analytics', 'Tracking analysis work with commits, branches, reviewable notebooks or scripts, data-change notes, and reproducible history.'),
('vite', 'Vite', 'Frontend', 'Vite supports web interface development through components, browser behavior, layout, state, accessibility, and performance considerations.'),
('vue-js', 'Vue.js', 'Frontend', 'Vue.js supports web interface development through components, browser behavior, layout, state, accessibility, and performance considerations.'),
('vuepress', 'VuePress', 'Frontend', 'Building documentation sites with VuePress pages, themes, navigation, Markdown content, Vue components, and static deployment.'),
('wcag', 'WCAG', 'Design & UX', 'Applying WCAG success criteria for perceivable, operable, understandable, and robust web experiences.'),
('web-performance-optimization', 'Web Performance Optimization', 'Frontend', 'Web Performance Optimization supports web interface development through components, browser behavior, layout, state, accessibility, and performance considerations.'),
('webpack', 'Webpack', 'Frontend', 'Webpack supports web interface development through components, browser behavior, layout, state, accessibility, and performance considerations.'),
('window-functions', 'Window Functions', 'Database', 'Writing SQL window functions with partitions, ordering, frames, ranking, offsets, rolling calculations, and grouped comparisons.'),
('workflow-orchestration', 'Workflow Orchestration', 'Tools & Workflow', 'Scheduling and coordinating dependent tasks with retries, parameters, monitoring, backfills, and failure recovery.');

-- Update canonical rows that already exist by slug.
UPDATE public.skill s
SET name = ss.name,
    category = ss.category,
    description = ss.description,
    is_active = true
FROM seed_shared_skill ss
WHERE s.slug = ss.slug;

-- Update rows that already exist by name but have a non-canonical slug.
-- Do not force the slug here; this avoids slug unique conflicts if a canonical row also exists.
UPDATE public.skill s
SET category = ss.category,
    description = ss.description,
    is_active = true
FROM seed_shared_skill ss
WHERE s.name = ss.name
  AND NOT EXISTS (
      SELECT 1
      FROM public.skill canonical
      WHERE canonical.slug = ss.slug
  );

-- Insert only missing shared skills. This avoids both slug and name unique conflicts.
INSERT INTO public.skill (slug, name, category, description, is_active)
SELECT ss.slug, ss.name, ss.category, ss.description, true
FROM seed_shared_skill ss
WHERE NOT EXISTS (
    SELECT 1
    FROM public.skill s
    WHERE s.slug = ss.slug OR s.name = ss.name
);

COMMIT;
